
name: My first code of github-action
on: push
jobs:
My Firts Job:
runs-on: ubuntu
steps:
- name: checkout code
  uses: action/checkout@v3
- name: Show the files
  run: ls -ltr
-name: Red REDADME
 run: cat README.md    
