
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: action/checkout@v6
      - name: welcome to read file
        run: echo "my first github action"
             ls -ltra
             cat README.md
      - name: grenate
        run: cowsay -f dargon "run coloer" >> dragon.txt       

      #- name: list the files
       # run: top 

      #- name: read file
        #run: cat README.md
