name: Hello World

on: push

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Steps
        run: |
          echo "Welcome to GitHub"
          echo " welcome to githubaction lernning"
